### ISSUE TITLE
Feature Request: Create the .npmrc file in each package

### ISSUE THREAD

**Issue by etc-tiago** [boltpkg/bolt#275]
| Title               | Description
| --------------------|------------
| Version             | 0.24.5
| Type                | feature
| node                | 12.16.3
| Operating System    | MacOs 10.15.4
| Short Description   | Create the .npmrc file in each package

# Detailed description

The `npm set registry https://registry.npmjs.org/ && echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}"> .npmrc` created the .npmrc file in the main folder, but the `bolt publish --access public` command ran in each folder separately, and it did not see .npmrc when executed.

I fixed package publishing by copying the .npmrc file for each package before running the publish command.

This could be done with an argument --npm-token like `bolt publish --access public --npm-token=****` or identifing the .npmrc on root folder and copying to packages.

**Comment by lukebatchelor** [comment]
I've not seen this be an issue for anyone else interestingly. Npm should traverse up directories until it finds an RC file (even up to your home dir if it exists).

Can you show how to reproduce this?

**Comment by etc-tiago** [comment]
My **.github/workflows/publish.yml**
```yml
name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - uses: actions/checkout@v1
      - run: |
          npm set progress=false
          npm set package-lock=false
          npm set registry https://registry.npmjs.org/ && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - run: yarn global add bolt
      - run: bolt
      - run: bolt publish --access public
```

secrets.NPM_TOKEN return a valid token.

When executed above, it returns the logs. This happens in all packages: 

**npm publish --access public npm ERR! 401 Unauthorized - PUT 
 https://registry.npmjs.org/package-name-example - You must be logged in to publish packages.**

So when I add an extra step:

```yml
steps:
    - uses: actions/setup-node@v1
       with:
          node-version: 12.16.x
    - uses: actions/checkout@v1
    - run: |
        npm set progress=false
        npm set package-lock=false
        npm set registry https://registry.npmjs.org/ && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
    - run: yarn global add bolt

    - run: |
       cp .npmrc /packages/example-1
       cp .npmrc /packages/example-2
      
    - run: bolt
    - run: bolt publish --access public
```

The bolt publish command succeeded in publishing to npm.
